# Generated by Django 5.2.10 on 2026-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_cierrecaja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso',
        ),
        migrations.AddField(
            model_name='producto',
            name='es_granel',
            field=models.BooleanField(default=False, verbose_name='¿Es Granel/Legumbre?'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=10),
        ),
    ]
