# Generated by Django 5.2.10 on 2026-01-10 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_producto_peso_producto_es_granel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Abonado')),
                ('nota', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota (Opcional)')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='principal.venta')),
            ],
        ),
    ]
