# Generated by Django 5.2.10 on 2026-01-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_abono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_mayorista',
            field=models.BooleanField(default=False, verbose_name='¿Es Cliente Especial/Mayorista?'),
        ),
    ]
